# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailmenus', '0022_auto_20170913_2125'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.Collection')),
            ],
        ),
        migrations.RemoveField(
            model_name='albumimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='albumimage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='albumpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='AlbumImage',
        ),
        migrations.DeleteModel(
            name='AlbumPage',
        ),
    ]
