# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formalsbooking', '0003_auto_20170718_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='wine_choice',
            field=models.CharField(blank=True, choices=[('NONE', 'None'), ('RED', 'Red'), ('WHITE', 'White')], default='NONE', max_length=50),
        ),
    ]
