# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_mainpagecarouselimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpagecarouselimage',
            old_name='caption',
            new_name='title',
        ),
        migrations.AddField(
            model_name='mainpagecarouselimage',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
