# Generated by Django 3.1.2 on 2020-10-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_custompage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericpage',
            name='sections',
        ),
    ]
