# Generated by Django 3.1.2 on 2020-10-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_genericpage_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompage',
            name='subtitle',
        ),
    ]
