# Generated by Django 3.1.2 on 2020-10-05 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_custompage_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericpage',
            name='subtitle',
        ),
    ]
