# Generated by Django 2.2.1 on 2019-06-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_appannouncement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appannouncement',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
