# Generated by Django 2.2.1 on 2019-06-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190605_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.TimeField()),
            ],
        ),
    ]
