# Generated by Django 3.0.3 on 2020-03-14 06:58

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20191218_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='sections',
            field=wagtail.core.fields.StreamField([('sections', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('colour', wagtail.core.blocks.CharBlock())]))], blank=True, null=True),
        ),
    ]
