# Generated by Django 3.1 on 2020-09-03 14:37

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_genericpage_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='sections',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock(blank=True)), ('sections', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('colour', wagtail.core.blocks.CharBlock(required=False)), ('body', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
    ]
