# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_personprofile_rolename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='description',
            field=models.TextField(),
        ),
    ]
