# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-02 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('home', '0013_auto_20170616_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagestaticcard',
            name='destination_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
