# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20170705_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='leader',
            field=models.CharField(default='President', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='club',
            name='facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='twitter_link',
            field=models.URLField(blank=True),
        ),
    ]
