# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20170705_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_blog_posts',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
