# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_documentpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='personprofile',
            name='facebook_link',
            field=models.URLField(blank=True),
        ),
    ]
