# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-28 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_personprofile_facebook_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
