# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-01 21:49
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20180828_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personprofile',
            name='facebook_link',
        ),
        migrations.AddField(
            model_name='personprofile',
            name='facebook_links',
            field=wagtail.wagtailcore.fields.StreamField((('facebook_link', wagtail.wagtailcore.blocks.URLBlock()),), null=True),
        ),
    ]
