# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-02 00:03
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20180902_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='facebook_links',
            field=wagtail.wagtailcore.fields.StreamField((('facebook_link', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock()), ('url', wagtail.wagtailcore.blocks.URLBlock())))),), blank=True, null=True),
        ),
    ]
